In [1]:
from strokepred.dataset import create_dataset
from strokepred.comapre_models import model_comparison
from IPython.display import display

In [2]:
display(create_dataset())

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,False,True,True,Private,Urban,228.69,36.6,formerly smoked,True
1,Female,61.0,False,False,True,Self-employed,Rural,202.21,28.1,never smoked,True
2,Male,80.0,False,True,True,Private,Rural,105.92,32.5,never smoked,True
3,Female,49.0,False,False,True,Private,Urban,171.23,34.4,smokes,True
4,Female,79.0,True,False,True,Self-employed,Rural,174.12,24.0,never smoked,True
...,...,...,...,...,...,...,...,...,...,...,...
5105,Female,80.0,True,False,True,Private,Urban,83.75,28.1,never smoked,False
5106,Female,81.0,False,False,True,Self-employed,Urban,125.20,40.0,never smoked,False
5107,Female,35.0,False,False,True,Self-employed,Rural,82.99,30.6,never smoked,False
5108,Male,51.0,False,False,True,Private,Rural,166.29,25.6,formerly smoked,False
5109,Female,44.0,False,False,True,Govt_job,Urban,85.28,26.2,Unknown,False

In [3]:
display(model_comparison)

,Model,Accuracy,AUC,Recall,Prec.,F1,Kappa,MCC,TT (Sec)
et,Extra Trees Classifier,0.9685,0.9916,0.9550,0.9815,0.9680,0.9369,0.9374,0.026
rf,Random Forest Classifier,0.9683,0.9949,0.9575,0.9786,0.9679,0.9365,0.9368,0.034
catboost,CatBoost Classifier,0.9678,0.9928,0.9512,0.9840,0.9672,0.9357,0.9363,0.579
lr,Logistic Regression,0.9638,0.9891,0.9340,0.9933,0.9627,0.9277,0.9295,0.076
gbc,Gradient Boosting Classifier,0.9613,0.9905,0.9398,0.9820,0.9604,0.9226,0.9236,0.048
ada,Ada Boost Classifier,0.9514,0.9881,0.9394,0.9628,0.9509,0.9029,0.9033,0.018
ridge,Ridge Classifier,0.9445,0.9886,0.8894,0.9995,0.9412,0.8890,0.8945,0.003
lda,Linear Discriminant Analysis,0.9443,0.9886,0.8889,0.9995,0.9409,0.8886,0.8942,0.002
dt,Decision Tree Classifier,0.9323,0.9323,0.9441,0.9228,0.9331,0.8646,0.8652,0.003
knn,K Neighbors Classifier,0.8838,0.9498,0.9794,0.8223,0.8939,0.7675,0.7823,0.007
svm,SVM - Linear Kernel,0.8564,0.9706,0.8670,0.8737,0.8553,0.7128,0.7364,0.005
nb,Naive Bayes,0.7072,0.9247,0.9844,0.6333,0.7707,0.4145,0.4982,0.002
qda,Quadratic Discriminant Analysis,0.5018,0.9637,1.0000,0.5007,0.6673,0.0042,0.0320,0.003

PatrzÄ…c na powyÅ¼szÄ… tabelÄ™ moÅ¼emy wyrÃ³Å¼niÄ‡ nastÄ™pujÄ…ce modele:

1. **Extra Trees Classifier** - jest to model z najwyÅ¼szym wynikiem "Accuracy" oraz "F1". RÃ³wnieÅ¼ naleÅ¼y do modeli z krÃ³tkim czasem uczenia.
2. **CatBoost Classifier** - mimo, Å¼e nie jest to model z najwyÅ¼szym wynikiem "Accuracy", jednakÅ¼e balansuje wszystkie miary, co daje mu wysokÄ… pozycjÄ™ w rankingu. Jest to model, ktÃ³ry bÄ™dzie bardziej "ostroÅ¼ny" w klasyfikacji.
3. **Random Forest Classifier** - osiÄ…ga 2 najwyÅ¼szy wynik "Accuracy" jednakÅ¼e, rozstrzaÅ‚ w innych miarach jest wiÄ™kszy niÅ¼ w przypadku modelu "Extra Trees Classifier" czy "CatBoost".

PowyÅ¼sza tabela pokrywa siÄ™ z wnykami [dotychczasowych badaÅ„Â dotyczÄ…cych przewidywania udarÃ³w](https://pubmed.ncbi.nlm.nih.gov/39355095/).

In [4]:
from pycaret.classification import predict_model
from strokepred.model import strokepred_model
from strokepred.dataset import balanced_dataset

sample_data = balanced_dataset().sample(5)

results = predict_model(strokepred_model, data=sample_data, verbose=False)

results = results.rename(columns={"stroke": "dataset stroke", "prediction_label": "predicted stroke"})
results = results.drop(columns=["prediction_score"])
results["predicted stroke"] = results["predicted stroke"].apply(bool)

display(results)

,age,hypertension,heart_disease,ever_married,avg_glucose_level,bmi,gender_Female,gender_Male,work_type_Govt_job,work_type_Never_worked,...,work_type_Self-employed,work_type_children,Residence_type_Rural,Residence_type_Urban,smoking_status_Unknown,smoking_status_formerly smoked,smoking_status_never smoked,smoking_status_smokes,dataset stroke,predicted stroke
6121,78.688194,False,True,True,106.080696,31.057014,True,True,False,False,...,True,False,True,True,False,True,True,False,True,True
1003,79.000000,False,False,True,113.410004,35.000000,False,True,False,False,...,True,False,False,True,False,False,True,False,False,False
1259,67.000000,False,False,True,81.680000,30.400000,True,False,False,False,...,False,False,True,False,False,False,True,False,False,False
888,71.000000,False,False,True,134.649994,32.400002,True,False,False,False,...,False,False,False,True,True,False,False,False,False,False
475,62.000000,False,False,True,136.179993,32.200001,False,True,False,False,...,True,False,True,False,True,False,False,False,False,False